---
argument_specs:
  main:
    short_description: Set up the checkpoint server.
    options:
      ec2_region:
        description: The AWS EC2 region the workshop is deployed in.
        type: str
        required: true
