---
- name: retrieve zone ID
  community.aws.route53_zone:
    zone: "{{workshop_dns_zone}}"
  register: AWSINFO

- name: retrieve route53 info
  community.aws.route53_info:
    type: A
    query: record_sets
    hosted_zone_id: "{{ AWSINFO.zone_id }}"
    start_record_name: "gitlab.{{ec2_name_prefix|lower}}.{{workshop_dns_zone}}"
    max_items: 1
  register: record_sets

- name: delete DNS entries for GitLab
  become: false
  community.aws.route53:
    state: "{{ s3_state }}"
    zone: "{{workshop_dns_zone}}"
    record: "gitlab.{{ec2_name_prefix|lower}}.{{workshop_dns_zone}}"
    type: A
    value: "{{ (records | first | first)['Value'] }}"
  vars:
    records: '{{record_sets.ResourceRecordSets | selectattr("Name", "match", "gitlab" + "." + ec2_name_prefix|lower + "." + workshop_dns_zone) | map(attribute="ResourceRecords") | list }}'
  when: records | length > 0
