---
- name: grab facts for node4 node
  amazon.aws.ec2_instance_info:
    region: "{{ ec2_region }}"
    filters:
      instance-state-name: running
      "tag:scenario_node4": "{{ec2_name_prefix}}-node4"
  register: node4_node_facts

- name: grab facts for node5 node
  amazon.aws.ec2_instance_info:
    region: "{{ ec2_region }}"
    filters:
      instance-state-name: running
      "tag:scenario_node5": "{{ec2_name_prefix}}-node5"
  register: node5_node_facts

- name: grab facts for node6 node
  amazon.aws.ec2_instance_info:
    region: "{{ ec2_region }}"
    filters:
      instance-state-name: running
      "tag:scenario_node6": "{{ec2_name_prefix}}-node6"
  register: node6_node_facts

- name: add hosts to groups (ANSIBLE RHEL MODE)
  add_host:
    name: "{{ item.tags.Name }}"
    username: "{{ student_user }}"
    student: "{{ item.tags.Student }}"
    short_name: "{{ item.tags.short_name }}"
    ansible_host: "{{ item.public_ip_address }}"
    ansible_user: "{{ item.tags.username }}"
    ansible_port: "{{ ssh_port }}"
    ansible_ssh_private_key_file: "{{ playbook_dir }}/{{ec2_name_prefix}}/{{ec2_name_prefix}}-private.pem"
    groups: lab_hosts,managed_nodes
  with_items:
    - "{{ node4_node_facts.instances }}"
    - "{{ node5_node_facts.instances }}"
    - "{{ node6_node_facts.instances }}"
  changed_when: false

- name: grab facts for isonode
  amazon.aws.ec2_instance_info:
    region: "{{ ec2_region }}"
    filters:
      instance-state-name: running
      "tag:Workshop_isonode": "{{ec2_name_prefix}}-isonode"
  register: isonode_node_facts
  when: create_cluster|bool

- name: grab facts for remotenode node
  amazon.aws.ec2_instance_info:
    region: "{{ ec2_region }}"
    filters:
      instance-state-name: running
      "tag:Workshop_remotenode": "{{ec2_name_prefix}}-remotenode"
  register: remotenode_node_facts
  when: create_cluster|bool

- name: add nodes for cluster lab to groups (ANSIBLE RHEL MODE)
  add_host:
    name: "{{ item.tags.Name }}"
    username: "{{ item.tags.Student }}"
    short_name: "{{ item.tags.short_name }}"
    ansible_host: "{{ item.public_ip_address }}"
    ansible_user: "{{ item.tags.username }}"
    ansible_port: "{{ ssh_port }}"
    ansible_ssh_private_key_file: "{{ playbook_dir }}/{{ec2_name_prefix}}/{{ec2_name_prefix}}-private.pem"
    groups: lab_hosts,managed_nodes
  with_items:
    - "{{ isonode_node_facts.instances }}"
    - "{{ remotenode_node_facts.instances }}"
  # changed_when: false
  when: create_cluster|bool
