---
- name: initial check setup
  hosts: localhost
  connection: local
  become: false
  gather_facts: true
  tasks:
    - name: download AAP
      include_role:
        name: ../../roles/aap_download

- name: configures automation controller node
  hosts: all
  gather_facts: true
  become: true
  vars:
    dns_type: none
    controllerinstall: true
    code_server: true
    username: student
    student: "{{ username }}"
  tasks:
    - name: print out ansible_host var
      debug:
        var: hostvars.controller
    - name: print ipv4 address
      debug:
        var: ansible_default_ipv4.address
    - include_role:
        name: ../../roles/user_accounts
    - include_role:
        name: ../../roles/common
    - include_role:
        name: ../../roles/connectivity_test
    - include_role:
        name: ../../roles/common
    - include_role:
        name: ../../roles/control_node
    - include_role:
        name: ../../roles/code_server
