---
- name: template out motd
  template:
    src: motd.j2
    dest: /etc/motd

- name: template ansible-navigator.yml into home directory
  template:
    src: ansible-navigator.yml.j2
    dest: "/home/{{ username }}/.ansible-navigator.yml"
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Put ssh-key in proper spot for student
  copy:
    src: "{{ output_dir }}/{{ ec2_name_prefix }}-private.pem"
    dest: "/home/{{ username }}/.ssh/id_rsa"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0400

- name: clean out /tmp/scenarios
  file:
    path: /tmp/scenarios
    state: absent

- name: Clone scenarios repo
  git:
    accept_hostkey: true
    clone: true
    dest: /tmp/scenarios
    repo: '{{ ansible_scenarios_url | default("https://github.com/heatmiser/rhel-soe-firstlight.git") }}'
    version: '{{ ansible_scenarios_version | default("main") }}'
    refspec: '{{ ansible_scenarios_refspec | default("") }}'
    force: true

- name: Create lab inventory directory
  file:
    state: directory
    path: /home/{{ username }}/lab_inventory

- name: Put student inventory in proper spot
  copy:
    src: "{{ output_dir }}/{{ student }}-instances.txt"
    dest: /home/{{ username }}/lab_inventory/hosts
    owner: "{{ username }}"
    group: "{{ username }}"
  when: username in inventory_hostname

- name: Copy instructor inventory to student1
  copy:
    src: "{{ output_dir }}/instructor_inventory.txt"
    dest: /tmp/instructor-inventory
    owner: "{{ username }}"
    group: "{{ username }}"
  when: '"student1-ansible-1" in inventory_hostname'

- name: Install ansible.cfg in home directory
  template:
    src: ansible.cfg.j2
    dest: "/etc/ansible/ansible.cfg"

# Pull specific EE for each scenario based on scenario name
- name: Pull execution environment for {{ scenario_type }} scenario
  become_user: "{{ username }}"
  containers.podman.podman_image:
    name: "{{ lookup('vars', scenario_type + '_ee') }}"
  register: podman_pull
  until: podman_pull is not failed
  retries: 5
