---
- name: retrieve as3 RPM from F5
  delegate_to: localhost
  connection: local
  block:
    - name: URL provided
      debug:
        var: as3_uri

    - name: Get releases for AS3
      ansible.builtin.uri:
        # Translate from GitHub repo or releases URL to api URL
        url: >-
          {{ as3_uri | regex_replace('^https://github.com/([^/]+)/([^./]+).*', 'https://api.github.com/repos/\1/\2/releases') }}
      register: r_get_f5_appsvcs_extension_releases

    - name: Set facts for AS3 release with RPM version
      ansible.builtin.set_fact:
        as3_release: "{{ __latest_rpm_asset.name }}"
        as3_release_tag: "{{ __latest_rpm_release.name }}"
        as3_release_rpm_url: "{{ __latest_rpm_asset.browser_download_url }}"
      vars:
        __latest_rpm_release: >-
          {{ r_get_f5_appsvcs_extension_releases.json | json_query('[?assets[?ends_with(name, `".noarch.rpm"`)]]|[0]') }}
        __latest_rpm_asset: >-
          {{ __latest_rpm_release | json_query('assets[?ends_with(name, `".noarch.rpm"`)]|[0]') }}

    - debug: var=as3_release
    - debug: var=as3_release_tag
    - debug: var=as3_release_rpm_url

    - name: Grab AS3 RPM from github
      ansible.builtin.get_url:
        url: "{{ as3_release_rpm_url }}"
        dest: "~/"
