---
# Make sure we can re-run the automation platform installer during a lab without killing code-server access
- name: update Ansible installer nginx configuration template to support code server
  blockinfile:
    block: "{{ lookup('template', 'nginx.conf') }}"
    dest: "{{ aap_dir }}/collections/ansible_collections/ansible/automation_platform_installer/roles/nginx/templates/nginx.conf"
    insertafter: "http {"

# Make the block inserted above conditional to only apply to ansible-1
- name: Add jinja conditional start
  lineinfile:
    path: "{{ aap_dir }}/collections/ansible_collections/ansible/automation_platform_installer/roles/nginx/templates/nginx.conf"
    insertafter: "http {"
    line: '{% raw %} {% if ansible_hostname == "ansible-1" %} {% endraw %}'

# Make the block inserted above conditional to only apply to ansible-1
- name: Add jinja conditional end
  lineinfile:
    path: "{{ aap_dir }}/collections/ansible_collections/ansible/automation_platform_installer/roles/nginx/templates/nginx.conf"
    insertbefore: "include(.*)/etc/nginx/mime.types;"
    line: '{% raw %} {% endif %} {% endraw %}'
