---
argument_specs:
  main:
    short_description: Set up webservers and scenario-specific config.
    options:
      short_name:
        description: The short name of the instance.
        type: str
        required: true
      scenario_type:
        description: The type of the scenario.
        type: str
        required: true
  f5:
    short_description: Configure webservers specific to the F5 scenario.
  security:
    short_description: Configure webservers specific to the security scenario.
  unsupported_scenario:
    short_description: Catch-all for unsupported scenario types.
    options:
      scenario_type:
        description: The type of the scenario.
        type: str
        required: true
