---
- name: Create EC2 instances for node7
  amazon.aws.ec2_instance:
    state: running
    network:
      assign_public_ip: true
    key_name: "{{ ec2_name_prefix }}-key"
    security_group: "{{ ec2_security_group }}"
    instance_type: "{{ ec2_info[rhel].size }}"
    image_id: "{{ node_ami_rhel_9.image_id }}"
    region: "{{ ec2_region }}"
    exact_count: "{{ student_total }}"
    filters:
      instance-state-name: running
      "tag:scenario_node7": "{{ ec2_name_prefix }}-node7"
    tags:
      scenario_node7: "{{ ec2_name_prefix }}-node7"
      scenario: "{{ ec2_name_prefix }}"
      uuid: "{{ ec2_name_prefix }}"
      guid: "{{ ec2_name_prefix }}"
      scenario_type: "{{ scenario_type }}"
      AWS_USERNAME: "{{ aws_user }}"
      owner: "{{ aws_user }}"
      Info: "AWS_USERNAME that provisioned this-> {{ aws_user }}"
      Linklight: "This was provisioned through the linklight provisioner"
      Students: "{{ student_total }}"
      short_name: "node7"
      username: "{{ ec2_info[rhel].username }}"
      ansible-scenarios: "true"
    wait: "{{ ec2_wait }}"
    vpc_subnet_id: "{{ ec2_vpc_subnet_id }}"
    volumes:
      - device_name: /dev/sda1
        ebs:
          volume_type: "{{ ec2_info[rhel].disk_volume_type }}"
          volume_size: "{{ ec2_info[rhel].disk_space }}"
          iops: "{{ ec2_info[rhel].disk_iops }}"
          throughput: "{{ ec2_info[rhel].disk_throughput }}"
          delete_on_termination: true
  register: sean_test

- debug:
    msg: "{{ sean_test }}"

- name: grab instance ids to tag node7
  amazon.aws.ec2_instance_info:
    region: "{{ ec2_region }}"
    filters:
      instance-state-name: running
      "tag:scenario_node7": "{{ ec2_name_prefix }}-node7"
  register: node7_output

- name: Ensure tags are present for node7
  amazon.aws.ec2_tag:
    region: "{{ ec2_region }}"
    resource: "{{ item.1.instance_id }}"
    state: present
    tags:
      Name: "{{ ec2_name_prefix }}-{{ student_user }}{{ item.0 + 1 }}-node7"
      Index: "{{ item[0] }}"
      Student: "{{ student_user }}{{ item.0 + 1 }}"
      launch_time: "{{ item.1.launch_time }}"
  with_indexed_items:
    - "{{ node7_output.instances }}"
  when: node7_output.instances|length > 0

- name: Associate IAM instance profile with node7
  amazon.aws.ec2_instance:
    instance_ids: "{{ item.1.instance_id }}"
    region: "{{ ec2_region }}"
    instance_role: "VPCLockDown_{{ ec2_name_prefix }}_student{{ item.0 + 1 }}"
    state: running
    wait: true
  with_indexed_items:
    - "{{ node7_output.instances }}"
  register: associate_iam_instance_profile
  until: associate_iam_instance_profile is not failed
  retries: 12
  delay: 10
  when:
    - node7_output.instances|length > 0
    - tower_node_aws_api_access|default(false)|bool

- name: Create EC2 instances for node8
  amazon.aws.ec2_instance:
    state: running
    network:
      assign_public_ip: true
    key_name: "{{ ec2_name_prefix }}-key"
    security_group: "{{ ec2_security_group }}"
    instance_type: "{{ ec2_info[rhel].size }}"
    image_id: "{{ node_ami_rhel_9.image_id }}"
    region: "{{ ec2_region }}"
    exact_count: "{{ student_total }}"
    filters:
      instance-state-name: running
      "tag:scenario_node8": "{{ ec2_name_prefix }}-node8"
    tags:
      scenario_node8: "{{ ec2_name_prefix }}-node8"
      scenario: "{{ ec2_name_prefix }}"
      uuid: "{{ ec2_name_prefix }}"
      guid: "{{ ec2_name_prefix }}"
      scenario_type: "{{ scenario_type }}"
      AWS_USERNAME: "{{ aws_user }}"
      owner: "{{ aws_user }}"
      Info: "AWS_USERNAME that provisioned this-> {{ aws_user }}"
      Linklight: "This was provisioned through the linklight provisioner"
      Students: "{{ student_total }}"
      short_name: "node8"
      username: "{{ ec2_info[rhel].username }}"
      ansible-scenarios: "true"
    wait: "{{ ec2_wait }}"
    vpc_subnet_id: "{{ ec2_vpc_subnet_id }}"
    volumes:
      - device_name: /dev/sda1
        ebs:
          volume_type: "{{ ec2_info[rhel].disk_volume_type }}"
          volume_size: "{{ ec2_info[rhel].disk_space }}"
          iops: "{{ ec2_info[rhel].disk_iops }}"
          throughput: "{{ ec2_info[rhel].disk_throughput }}"
          delete_on_termination: true

- name: grab instance ids to tag node8
  amazon.aws.ec2_instance_info:
    region: "{{ ec2_region }}"
    filters:
      instance-state-name: running
      "tag:scenario_node8": "{{ ec2_name_prefix }}-node8"
  register: node8_output

- name: Ensure tags are present for node8
  amazon.aws.ec2_tag:
    region: "{{ ec2_region }}"
    resource: "{{ item.1.instance_id }}"
    state: present
    tags:
      Name: "{{ ec2_name_prefix }}-{{ student_user }}{{ item.0 + 1 }}-node8"
      Index: "{{ item[0] }}"
      Student: "{{ student_user }}{{ item.0 + 1 }}"
      launch_time: "{{ item.1.launch_time }}"
  with_indexed_items:
    - "{{ node8_output.instances }}"
  when: node8_output.instances|length > 0

- name: Associate IAM instance profile with node8
  amazon.aws.ec2_instance:
    instance_ids: "{{ item.1.instance_id }}"
    region: "{{ ec2_region }}"
    instance_role: "VPCLockDown_{{ ec2_name_prefix }}_student{{ item.0 + 1 }}"
    state: running
    wait: true
  with_indexed_items:
    - "{{ node8_output.instances }}"
  register: associate_iam_instance_profile
  until: associate_iam_instance_profile is not failed
  retries: 12
  delay: 10
  when:
    - node8_output.instances|length > 0
    - tower_node_aws_api_access|default(false)|bool

- name: Create EC2 instances for node9
  amazon.aws.ec2_instance:
    state: running
    network:
      assign_public_ip: true
    key_name: "{{ ec2_name_prefix }}-key"
    security_group: "{{ ec2_security_group }}"
    instance_type: "{{ ec2_info[rhel].size }}"
    image_id: "{{ node_ami_rhel_9.image_id }}"
    region: "{{ ec2_region }}"
    exact_count: "{{ student_total }}"
    filters:
      instance-state-name: running
      "tag:scenario_node9": "{{ ec2_name_prefix }}-node9"
    tags:
      scenario_node9: "{{ ec2_name_prefix }}-node9"
      scenario: "{{ ec2_name_prefix }}"
      uuid: "{{ ec2_name_prefix }}"
      guid: "{{ ec2_name_prefix }}"
      scenario_type: "{{ scenario_type }}"
      AWS_USERNAME: "{{ aws_user }}"
      owner: "{{ aws_user }}"
      Info: "AWS_USERNAME that provisioned this-> {{ aws_user }}"
      Linklight: "This was provisioned through the linklight provisioner"
      Students: "{{ student_total }}"
      short_name: "node9"
      username: "{{ ec2_info[rhel].username }}"
      ansible-scenarios: "true"
    wait: "{{ ec2_wait }}"
    vpc_subnet_id: "{{ ec2_vpc_subnet_id }}"
    volumes:
      - device_name: /dev/sda1
        ebs:
          volume_type: "{{ ec2_info[rhel].disk_volume_type }}"
          volume_size: "{{ ec2_info[rhel].disk_space }}"
          iops: "{{ ec2_info[rhel].disk_iops }}"
          throughput: "{{ ec2_info[rhel].disk_throughput }}"
          delete_on_termination: true

- name: grab instance ids to tag node9
  amazon.aws.ec2_instance_info:
    region: "{{ ec2_region }}"
    filters:
      instance-state-name: running
      "tag:scenario_node9": "{{ ec2_name_prefix }}-node9"
  register: node9_output

- name: Ensure tags are present for node9
  amazon.aws.ec2_tag:
    region: "{{ ec2_region }}"
    resource: "{{ item.1.instance_id }}"
    state: present
    tags:
      Name: "{{ ec2_name_prefix }}-{{ student_user }}{{ item.0 + 1 }}-node9"
      Index: "{{ item[0] }}"
      Student: "{{ student_user }}{{ item.0 + 1 }}"
      launch_time: "{{ item.1.launch_time }}"
  with_indexed_items:
    - "{{ node9_output.instances }}"
  when: node9_output.instances|length > 0

- name: Associate IAM instance profile with node9
  amazon.aws.ec2_instance:
    instance_ids: "{{ item.1.instance_id }}"
    region: "{{ ec2_region }}"
    instance_role: "VPCLockDown_{{ ec2_name_prefix }}_student{{ item.0 + 1 }}"
    state: running
    wait: true
  with_indexed_items:
    - "{{ node9_output.instances }}"
  register: associate_iam_instance_profile
  until: associate_iam_instance_profile is not failed
  retries: 12
  delay: 10
  when:
    - node9_output.instances|length > 0
    - tower_node_aws_api_access|default(false)|bool

# Create isolated/remote node for Adv Tower lab when cluster install

- name: Create EC2 instances for isonode
  amazon.aws.ec2_instance:
    state: running
    network:
      assign_public_ip: true
    key_name: "{{ ec2_name_prefix }}-key"
    security_group: "{{ ec2_security_group }}"
    instance_type: "{{ ec2_info[rhel].size }}"
    image_id: "{{ node_ami_rhel_9.image_id }}"
    region: "{{ ec2_region }}"
    exact_count: "{{ student_total }}"
    filters:
      instance-state-name: running
      "tag:scenario_isonode": "{{ ec2_name_prefix }}-isonode"
    tags:
      scenario_isonode: "{{ ec2_name_prefix }}-isonode"
      scenario: "{{ ec2_name_prefix }}"
      scenario_type: "{{ scenario_type }}"
      AWS_USERNAME: "{{ aws_user }}"
      owner: "{{ aws_user }}"
      Info: "AWS_USERNAME that provisioned this-> {{ aws_user }}"
      Linklight: "This was provisioned through the linklight provisioner"
      Students: "{{ student_total }}"
      short_name: "isonode"
      username: "{{ ec2_info[rhel].username }}"
      ansible-scenarios: "true"
    wait: "{{ ec2_wait }}"
    vpc_subnet_id: "{{ ec2_vpc_subnet_id }}"
    volumes:
      - device_name: /dev/sda1
        ebs:
          volume_type: "{{ ec2_info[rhel].disk_volume_type }}"
          volume_size: "{{ ec2_info[rhel].disk_space }}"
          iops: "{{ ec2_info[rhel].disk_iops }}"
          throughput: "{{ ec2_info[rhel].disk_throughput }}"
          delete_on_termination: true
  when: create_cluster|bool

- name: grab instance ids to tag isonode
  amazon.aws.ec2_instance_info:
    region: "{{ ec2_region }}"
    filters:
      instance-state-name: running
      "tag:scenario_isonode": "{{ ec2_name_prefix }}-isonode"
  register: isonode_output
  when: create_cluster|bool

- name: Ensure tags are present for isonode
  amazon.aws.ec2_tag:
    region: "{{ ec2_region }}"
    resource: "{{ item.1.instance_id }}"
    state: present
    tags:
      Name: "{{ ec2_name_prefix }}-student{{ item.0 + 1 }}-isonode"
      Index: "{{ item[0] }}"
      Student: "student{{ item.0 + 1 }}"
      launch_time: "{{ item.1.launch_time }}"
  with_indexed_items:
    - "{{ isonode_output.instances }}"
  when: create_cluster|bool and isonode_output.instances|length > 0

- name: Create EC2 instances for remotenode
  amazon.aws.ec2_instance:
    state: running
    network:
      assign_public_ip: true
    key_name: "{{ ec2_name_prefix }}-key"
    security_group: "{{ ec2_security_group }}"
    instance_type: "{{ ec2_info[rhel].size }}"
    image_id: "{{ node_ami_rhel_9.image_id }}"
    region: "{{ ec2_region }}"
    exact_count: "{{ student_total }}"
    filters:
      instance-state-name: running
      "tag:scenario_remotenode": "{{ ec2_name_prefix }}-remotenode"
    tags:
      scenario_remotenode: "{{ ec2_name_prefix }}-remotenode"
      scenario: "{{ ec2_name_prefix }}"
      scenario_type: "{{ scenario_type }}"
      AWS_USERNAME: "{{ aws_user }}"
      owner: "{{ aws_user }}"
      Info: "AWS_USERNAME that provisioned this-> {{ aws_user }}"
      Linklight: "This was provisioned through the linklight provisioner"
      Students: "{{ student_total }}"
      short_name: "remotenode"
      username: "{{ ec2_info[rhel].username }}"
      ansible-scenarios: "true"
    wait: "{{ ec2_wait }}"
    vpc_subnet_id: "{{ ec2_vpc_subnet_id }}"
    volumes:
      - device_name: /dev/sda1
        ebs:
          volume_type: "{{ ec2_info[rhel].disk_volume_type }}"
          volume_size: "{{ ec2_info[rhel].disk_space }}"
          iops: "{{ ec2_info[rhel].disk_iops }}"
          throughput: "{{ ec2_info[rhel].disk_throughput }}"
          delete_on_termination: true
  when: create_cluster|bool

- name: grab instance ids to tag isonode
  amazon.aws.ec2_instance_info:
    region: "{{ ec2_region }}"
    filters:
      instance-state-name: running
      "tag:scenario_remotenode": "{{ ec2_name_prefix }}-remotenode"
  register: remotenode_output
  when: create_cluster|bool

- name: Ensure tags are present for remotenode
  amazon.aws.ec2_tag:
    region: "{{ ec2_region }}"
    resource: "{{ item.1.instance_id }}"
    state: present
    tags:
      Name: "{{ ec2_name_prefix }}-student{{ item.0 + 1 }}-remotenode"
      Index: "{{ item[0] }}"
      Student: "student{{ item.0 + 1 }}"
      launch_time: "{{ item.1.launch_time }}"
  with_indexed_items:
    - "{{ remotenode_output.instances }}"
  when: create_cluster|bool and remotenode_output.instances|length > 0
