---
- name: configure hostname
  hostname:
    name: "{{short_name}}"

- name: setup scenario specific webserver information
  include_tasks: "{{item}}"
  with_first_found:
    - "{{role_path}}/tasks/{{scenario_type}}.yml"
    - "{{role_path}}/tasks/unsupported_scenario.yml"
