---
- name: CONFIGURE scenario WEBSERVERS FOR DEVOPS
  hosts: lab_hosts
  become: true
  gather_facts: false
  tasks:
    - include_role:
        name: ../../roles/devops
      when: scenario_type == "devops"
