---
- name: Enable TCP port 9000 for php-fpm
  lineinfile:
    path: /etc/php-fpm.d/www.conf
    regexp: '^listen ='
    line: 'listen = 127.0.0.1:9000'
  notify: restart php-fpm

- name: Start Services
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items:
    - mariadb
    - php-fpm
  notify: restart nginx

- name: Set permissions on the PHP Session directory
  file:
    path: /var/lib/php/session/
    owner: nginx
    group: nginx
    mode: 0777
    state: directory

- name: Create users directory on server
  file:
    path: /usr/share/nginx/html/
    state: directory

- name: Copy users file to server
  template:
    src: templates/index.php.j2
    dest: /usr/share/nginx/html/index.php

- name: Copy files over to attendance node
  copy:
    src: "{{ item }}"
    dest: "/usr/share/nginx/html/{{ item }}"
  loop:
    - redhat-ansible-logo.svg
    - redhat-logo.svg
    - style.css
    - favicon.ico

- name: Copy list file to server
  template:
    src: templates/list.php.j2
    dest: /usr/share/nginx/html/list.php

- name: Install PyMySQL
  pip:
    name: PyMySQL

- name: make sure any previous runs 'scenario' database is reset
  community.mysql.mysql_db:
    name: scenario
    state: absent

- name: Create a new database with name 'scenario'
  community.mysql.mysql_db:
    name: scenario
    state: present

- name: Copy SQL template to server
  template:
    src: templates/scenario.sql.j2
    dest: /tmp/scenario.sql
  register: scenariosql

- name: Import SQL file into scenario database
  community.mysql.mysql_db:
    state: import
    name: scenario
    target: /tmp/scenario.sql
