---
- name: initial check setup
  hosts: localhost
  connection: local
  become: false
  gather_facts: true
  tasks:
    - name: scenario collection final check
      block:
        - name: run pre-check role to make sure scenario will complete provisioning
          include_role:
            name: ../roles/scenario_check_setup

        - name: run AWS check setup if using AWS
          include_role:
            name: ../roles/aws_check_setup

      rescue:
        - name: Error with setup
          fail:
            msg: The provisioner has failed during initial check_setup, please scroll up to see exact error.  Open an issue on https://github.com/ansible/scenarios/issues

- name: Create AWS infrastructure
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  tasks:
    - include_role:
        name: ../roles/manage_ec2_infra
