---
argument_specs:
  main:
    short_description: General configuration for the control node.
    options:
      f5_ee:
        type: str
        description: f5 execution environment
        default: "quay.io/acme_corp/f5_ee:latest"
      security_ee:
        type: str
        description: security execution environment
        default: "quay.io/acme_corp/security_ee:latest"
      rhel_ee:
        type: str
        description: rhel execution environment
        default: "registry.redhat.io/ansible-automation-platform-20-early-access/ee-supported-rhel8:2.0.0"
      network_ee:
        type: str
        description: network execution environment
        default: "registry.redhat.io/ansible-automation-platform-20-early-access/ee-supported-rhel8:2.0.0"
      rhel_90_ee:
        type: str
        description: rhel_90 execution environment
        default: "quay.io/acme_corp/rhel_90_ee:latest"
      windows_ee:
        type: str
        description: windows execution environment
        default: "quay.io/acme_corp/windows_ee:latest"
      smart_mgmt_ee:
        type: str
        description: smart_mgmt execution environment
        default: "quay.io/s4v0/ee-automated-smart-mgmt-29:latest"
      username:
        description: The scenario username.
        type: str
        required: true
      ec2_name_prefix:
        description: A prefix for EC2 and DNS resources.
        type: str
        required: true
      ansible_scenarios_url:
        description: The repository url for ansible/scenarios.
        type: str
        required: false
      ansible_scenarios_version:
        description: The repository version for ansible/scenarios.
        type: str
        required: false
      ansible_scenarios_refspec:
        description: The repository refspec for ansible/scenarios.
        type: str
        required: false
      exercise_src_location:
        description: The location of the exercise in ansible/scenarios.
        type: str
        required: false
      scenario_type:
        description: The type of the scenario.
        type: str
        required: true
      admin_password:
        description: The Ansible Tower admin password.
        type: str
        required: true
      controllerinstall:
        description: Whether to install automation controller.
        type: bool
        required: false
        default: false
      tower_node_aws_api_access:
        description: Whether Ansible controller has access ot the AWS API.
        type: bool
        required: false
        default: false
  devops:
    short_description: Configure the devops scenario.
    options:
      username:
        description: The scenario username.
        type: str
        required: true
  f5:
    short_description: Configure the F5 scenario.
    options:
      username:
        description: The scenario username.
        type: str
        required: true
  network:
    short_description: Configure the network scenario.
  package_dependencies:
    short_description: Install general package dependencies for scenarios.
  route53_update:
    short_description: Configure the Route53 update service.
    options:
      username:
        description: The scenario username.
        type: str
        required: true
  security:
    short_description: Configure the security scenario
  tower:
    short_description: Configure Ansible Controller.
    options:
      default_platform_url:
        description: The default URL to the Ansible Platform .tar.gz installer.
        type: str
        required: true
      admin_password:
        description: The automation controller admin password.
        type: str
        required: true
      tower_license:
        description: The tower license file contents.
        type: str
        required: true
      create_cluster:
        description: Whether to create an automation controller cluster.
        type: bool
        required: true
      gpgcheck:
        description: Whether to perform GPG checking on repository packages.
        type: int
        required: false
        default: 0
        choices:
          - 0
          - 1
      aw_repo_url:
        description: The repository URL for Ansible Tower installation.
        type: str
        required: false
        default: https://releases.ansible.com/ansible-tower/
  unsupported_scenario:
    short_description: Catch-all for unsupported scenario types.
    options:
      scenario_type:
        description: The type of the scenario.
        type: str
        required: true
  venv:
    short_description: Set up a virtual environment for Ansible Tower.
    options:
      admin_password:
        description: The Ansible Tower admin password.
        type: str
        required: true
  windows:
    short_description: Set up Windows scenario prerequisites.
