---
argument_specs:
  main:
    short_description: scenario setup and config preflight verification.
    options:
      ec2_name_prefix:
        description: A prefix for EC2 and DNS resources.
        type: str
        required: true
      scenario_dns_zone:
        description: The base DNS zone for the scenario.
        type: str
        required: true
      scenario_type:
        description: The type of the scenario.
        type: str
        required: true
      valid_scenario_types:
        description: A list of valid scenario types.
        type: list
        elements: str
        required: true
      dns_type:
        description: The system that manages DNS, e.g. "aws"
        type: str
        required: true
      valid_dns_type:
        description: A list of valid DNS provider types.
        type: list
        elements: str
        required: true
      network_type:
        description: The type of the network provider.
        type: str
        required: true
      valid_network_types:
        description: A list of valid network provider types.
        type: list
        elements: str
        required: true
      security_console:
        description: The type of the security console.
        type: str
        required: true
      valid_security_console_types:
        description: A list of valid security console types.
        type: list
        elements: str
        required: true
      admin_password:
        description: The scenario admin password.
        type: str
        required: true
      default_tower37_url:
        description: A fallback URL for Ansible Tower 3.7.
        type: str
        required: false
      default_tower38_url:
        description: A fallback URL for Ansible Tower 3.8.
        type: str
        required: false
      controllerinstall:
        description: Whether to install Ansible Tower.
        type: bool
        required: true
  network:
    short_description: Verify scenario setup for the network scenario.
    options:
  security:
    short_description: Verify scenario setup for the security scenario.
    options:
      windows_password:
        description: The Windows password.
        type: str
        required: true
  unsupported_scenario:
    short_description: Catch-all for unsupported scenario types.
    options:
      scenario_type:
        description: The type of the scenario.
        type: str
        required: true
  windows:
    short_description: Verify scenario setup for Windows scenarios.
